// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using Unity.Services.CloudCode;

namespace Monopoly.Backend.Gateway.Services
{
    public class RatingServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public RatingServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<int> GetMMR()
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "RatingService",
                "GetMMR",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<int> UpdateMMR(bool didWin)
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "RatingService",
                "UpdateMMR",
                new Dictionary<string, object>()
                {
                    {"didWin", didWin},
                });
        }

        public async Task<int> ResetMMR()
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "RatingService",
                "ResetMMR",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
