// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;
using Unity.Services.CloudCode;

namespace Monopoly.Backend.Gateway.Services
{
    public class RankedServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public RankedServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<int> GetELO()
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "RankedService",
                "GetELO",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
